@host=http://localhost:3000

### Create a new user
POST {{host}}/auth/signup
content-type: application/json

{
  "email": "asdf@asdf332.com",
  "password": "asdfasdf32"
}

### Find a particular user with a given ID
GET {{host}}/auth/3

### Find all users with a given email
GET {{host}}/auth?email=asdf@asdf2.com

### Delete a user given id
DELETE {{host}}/auth/233

### Update a user
PATCH {{host}}/auth/3
content-type: application/json

{
  "email": "aaaaaa@aaaaa.com"
}

### Set a color
GET {{host}}/auth/colors/red

### Get ad color
GET {{host}}/auth/colors